### ISSUE TITLE
FDR control

### ISSUE THREAD

**Issue by Takahiro0113** [jokamoto97/INTACT#1]
Hi,

In your main paper Bayesian FDR control on gene-level PIP is performed, but an output of the function "intact" seems to have no information about it.
How can I gain these metrics? Any other tools?
Thank you in advance.

Taka

**Comment by jokamoto97** [comment]
Hi Taka,

Thanks for the question! I just updated the package so that it now includes the function `fdr_rst`, which can perform Bayesian FDR control on the INTACT posterior probabilities, as we did in the paper. The function takes 2 arguments:

1) The posterior output from INTACT 
2) Your target FDR control level (equal to 0.05 as default)

The function will output an n x 2 data frame where the first column is the posterior input and the second denotes which genes passed the significance threshold.

Hope this helps!

**Comment by Takahiro0113** [comment]
Great work! It worked as I have desired.
Thanks a lot!
